# GitHub Actions
# https://docs.github.com/en/actions/using-workflows
name: Cypress single tests

on: [push, workflow_dispatch]

jobs:
  test1:
    name: Cypress test
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    # install a specific version of Node using
    # https://github.com/actions/setup-node
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20


    - name: install dependencies and verify Cypress
      env:
        # make sure every Cypress install prints minimal information
        CI: 1
      # print Cypress and OS info
      run: |
        npm ci
        npx cypress verify
        npx cypress info
        npx cypress version
        npx cypress version --component package
        npx cypress version --component binary
        npx cypress version --component electron
        npx cypress version --component node

  

